# This is a basic workflow to help you get started with Actions
# referencia da montagem https://theabodeofcode.com/running-postman-collections-in-github-action-workflows/ 
name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  api-test:
  
    runs-on:  ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    # INstall Node on the runner
    - name: Install Node
      uses: actions/setup-node@v1
      with: 
        node-version: '12.x'
     
   # Make directory to upload the test results
    - name: Criando pasta para armazenador os artefatos do teste
      run: mkdir -p artefatos
    
    # Make directory to upload the test results
    - name: Criando pasta para armazenador relatorio
      run: mkdir -p relatorio
      

    # Run the POSTMAN collection
    - name: Run POSTMAN collection
      run: |
       newman run SpaceX.postman_collection.json -e SpaceX.postman_environment.json -r cli,htmlextra --reporter-htmlextra-export testResults/htmlreport.html --reporter-htmlextra-darkTheme  > testResults/runreport1.html


    # Upload the contents of Test Results directory to workspace
    - name: Output the run Details
      uses: actions/upload-artifact@v2
      with: 
       name: RunReports
       path: testResults
   
    #deploy relatorio no github actions
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: artefatos # The folder the action should deploy.
        
        
        
        
        
