# This is a basic workflow to help you get started with Actions
# referencia da montagem https://theabodeofcode.com/running-postman-collections-in-github-action-workflows/ 
name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      # Checkout na branch
      - name: Checkout Repository
        uses: actions/checkout@master
        
      # Install Node.js environment
      - name: set up node
        uses: actions/setup-node@v1
        with: 
          node-version: '14.x'

      # Install newman
      - name: Install newman
        run: | 
         npm install -g newman
         npm install -g newman-reporter-htmlextra
         
      # armazenar resultados
      - name: Make Directory for results
        run: mkdir -p testResults
        
      # rodar os cenários
      - name: Make Directory for results
        run: newman run SpaceX.postman_collection.json -e SpaceX.postman_environment.json
        
      # Install Node.js environment
      - name: Output the run Details
        with: 
         name: RunReports
         path: testResults
        
